repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: mixed-line-ending
    args: ['--fix=auto']  # replace 'auto' with 'lf' to enforce Linux/Mac line endings or 'crlf' for Windows

## Automatically fix flake8 errors due to unused vars or imports:
# - repo: https://github.com/myint/autoflake.git
#   rev: v1.4
#   hooks:
#   - id: autoflake
#     args: [
#       --in-place,
#       --remove-all-unused-imports,
#       --remove-unused-variables,
#     ]

# Deactivate isort temporarily
#- repo: https://github.com/pycqa/isort
#  rev: 5.8.0
#  hooks:
#  - id: isort
#    args: ["--profile", "black", "--multi-line", "3"]

- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
  - id: black
    language_version: python3

# Deactivate flake8 temporarily
#- repo: https://gitlab.com/pycqa/flake8
#  rev: 3.8.4
#  hooks:
#  - id: flake8
#    args: [
#      --max-line-length=88,
#    ]
  ## You can add flake8 plugins via `additional_dependencies`:
  #  additional_dependencies: [flake8-bugbear]
